<table >
    <thead>
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Text</th>
        <th>News Site</th>
        <th>Published at</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>${article.id}</td>
            <td>${article.title}</td>
            <td>${article.summary}</td>
            <td>${article.newsSite}</td>
            <td>${article.publishedAt}</td>

        </tr>
    </tbody>
</table>